version: '3.8'

services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: cosmic-market-oracle-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - cosmic-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: cosmic-market-oracle-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - cosmic-network

  # Loki for log aggregation
  loki:
    image: grafana/loki:latest
    container_name: cosmic-market-oracle-loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - cosmic-network

  # Promtail for log collection
  promtail:
    image: grafana/promtail:latest
    container_name: cosmic-market-oracle-promtail
    restart: always
    volumes:
      - ./logs:/var/log/cosmic-market-oracle
      - ./monitoring/promtail:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - cosmic-network
    depends_on:
      - loki

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cosmic-market-oracle-jaeger
    restart: always
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # Collector HTTP
      - "6831:6831/udp"  # Agent
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    networks:
      - cosmic-network

volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  cosmic-network:
    external: true
